# Generated by Django 3.1.5 on 2021-03-19 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('x', models.SmallIntegerField(default=0)),
                ('y', models.SmallIntegerField(default=0)),
                ('z', models.SmallIntegerField(default=0)),
                ('status', models.BooleanField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_line', models.CharField(max_length=14)),
                ('customer_no', models.CharField(max_length=15)),
                ('sales_order_no', models.CharField(max_length=7)),
                ('customer_name', models.CharField(max_length=50)),
                ('linekey', models.CharField(max_length=6)),
                ('item_code', models.CharField(max_length=30)),
                ('item_cod_desc', models.CharField(max_length=64)),
                ('so_header', models.DateField()),
                ('prom_date', models.DateField()),
                ('clear_date', models.DateField()),
                ('exp_date_i', models.DateField()),
                ('exp_date_f', models.DateField()),
                ('qty', models.IntegerField()),
                ('qty_shipped', models.IntegerField()),
                ('unit_price', models.CharField(max_length=20)),
                ('production_notes', models.CharField(max_length=250)),
                ('qty_on_hand', models.IntegerField()),
                ('rma_number', models.IntegerField()),
                ('drop_ship', models.CharField(max_length=2)),
                ('comments', models.CharField(max_length=250)),
            ],
        ),
    ]
