# Generated by Django 3.1.5 on 2021-04-11 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='progress',
            field=models.IntegerField(default=100),
        ),
    ]
