# Generated by Django 3.1.5 on 2021-03-19 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('item_code', models.CharField(max_length=30)),
                ('item_cod_desc', models.CharField(max_length=64)),
                ('link', models.CharField(max_length=512)),
                ('level', models.SmallIntegerField()),
                ('status', models.BooleanField(default=1)),
            ],
        ),
    ]
