# Generated by Django 3.1.5 on 2021-03-19 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(max_length=64)),
                ('date', models.DateField()),
                ('status', models.BooleanField(default=1)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product', to='live.product')),
            ],
        ),
    ]
