# Generated by Django 3.1.5 on 2021-04-11 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0002_product_progress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='progress',
            new_name='steps',
        ),
    ]
