# Generated by Django 3.1.5 on 2021-04-11 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0004_auto_20210411_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prgr',
            field=models.IntegerField(default=0),
        ),
    ]
