# Generated by Django 3.1.5 on 2021-03-19 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0004_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_comment', to='live.product'),
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_log', to='live.product')),
                ('status_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status', to='live.status')),
            ],
        ),
    ]
