# Generated by Django 3.1.5 on 2021-04-11 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0005_product_prgr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='steps',
            field=models.IntegerField(default=10),
        ),
    ]
