# Generated by Django 3.1.5 on 2021-03-19 22:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('live', '0006_profile_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_location',
            name='location_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='location_profile', to='live.location'),
        ),
        migrations.AlterField(
            model_name='profile_location',
            name='profile_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profile', to='live.profile'),
        ),
        migrations.CreateModel(
            name='Location_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='location_user', to='live.location')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
