# Generated by Django 3.1.5 on 2021-04-11 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0006_auto_20210411_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('NEW', 'NEW'), ('KITTING', 'KITTING'), ('WAITING', 'WAITING'), ('KITTED', 'KITTED'), ('FCT in PROGRESS', 'FCT in PROGRESS'), ('ON HOLD', 'ON HOLD'), ('Mech Assy', 'Mech Assy'), ('FCT PASSED', 'FCT PASSED'), ('BURN-IN', 'BURN-IN'), ('QA', 'QA'), ('SHIPPING', 'SHIPPING'), ('NAN', 'NA')], default='NEW', max_length=32),
        ),
    ]
