# Generated by Django 3.1.5 on 2021-04-17 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0007_auto_20210411_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='comments',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
