# Generated by Django 3.1.5 on 2021-04-18 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0008_auto_20210417_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='notes_deprecated',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='product',
            name='steps',
            field=models.IntegerField(default=100),
        ),
    ]
