# Generated by Django 3.1.5 on 2021-04-19 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0009_auto_20210418_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='profile',
            field=models.CharField(choices=[('P0', 'QA'), ('P1', 'FCT -> QA'), ('P2', 'FCT -> Burn In -> QA'), ('P3', 'FCT -> Production -> Burn In -> QA'), ('P4', 'Production -> Burn In -> QA'), ('P98', 'ON-HOLD'), ('P99', 'NA')], default='P0', max_length=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('NEW', 'NEW'), ('KITTING', 'KITTING'), ('WAITING', 'WAITING'), ('KITTED', 'KITTED'), ('FCT in PROGRESS', 'FCT in PROGRESS'), ('ON HOLD', 'ON HOLD'), ('BUILDING', 'BUILDING'), ('FCT PASSED', 'FCT PASSED'), ('BURN-IN', 'BURN-IN'), ('QA', 'QA'), ('SHIPPING', 'SHIPPING'), ('NAN', 'NA')], default='NEW', max_length=32),
        ),
    ]
