# Generated by Django 3.1.5 on 2021-04-19 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0010_auto_20210419_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='profile',
            field=models.CharField(choices=[('P0', 'QA'), ('P1', 'FCT -> QA'), ('P2', 'FCT -> Burn In -> QA'), ('P3', 'FCT -> Production -> Burn In -> QA'), ('P4', 'Production -> Burn In -> QA'), ('P5', 'Burn In -> QA'), ('P98', 'ON-HOLD'), ('P99', 'NA')], default='P0', max_length=3),
        ),
    ]
